version: "3"
services:
 puppetagent:
  image: thierryjl/puppet-agent53
  deploy:
   replicas: 4
   resources:
    limits:
     cpus: "0.1"
     memory: 50M
   restart_policy:
    condition: on-failure
  ports:
   - "8140:8140"
  networks:
   - "puppet"
networks:
 puppet:

