# Use root/example as user/password credentials
#
# To run :
# Run docker stack deploy -c tj-mysql.yml mysql (or docker-compose -f tj-mysql up), 
# wait for it to initialize completely, and visit http://swarm-ip:8080, http://localhost:8080, or http://host-ip:8080 (as appropriate)

version: '3.1'

version: '3.1'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
